export const movies = [
  {
    poster: 'assets/images/wolf-wall-street.jpg',
    title: 'The Wolf of Wall Street',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort's autobiography.",
  },
  {
    poster: 'assets/images/inception.jpg',
    title: 'Inception',
    genre: ['action', 'mystery,', 'thriller'],
    year: 2010,
    country: 'USA',
    rating: 8.8,
    actors: [
      'Leonardo DiCaprio',
      'Joseph Gordon-Levitt',
      'Ellen Page',
      'Tom Hardy',
      'Ken Watanabe',
    ],
    duration: 148,
    description:
      "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: inception, the implantation of another person's idea into a target's subconscious.",
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
];
