export const upcomingMovies = [
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 8.2,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
  {
    poster: 'assets/images/green-book.jpg',
    title: 'Green Book',
    genre: ['crime', 'drama', 'comedy'],
    year: 2018,
    country: 'USA',
    rating: 4,
    actors: [
      'Cristin Milioti',
      'Matthew McConaughey',
      'Jon Bernthal',
      'Zineb Oukach',
      'JTO Connor',
    ],
    duration: 180,
    description:
      'Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.',
  },
];
